### ISSUE TITLE
SYS.2.A: The IP Camera shall transmit video to the Data Server (1) via the Router (8)

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/ASM-docs#7]

**Comment by kymiyamo** [comment]
Before we test the IP Camera for a long duration, I need to run a few initial tests to ensure the Pi can withstand that large amount of data.

**Comment by ntlhui** [comment]
Some issues with video stability, noting timestamp issues, noting video length issues, eta 2/13
